// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var fibSequence = [1,0]
var sum = 0
var total = 0

while ( sum < 4000000) {
  sum = fibSequence[0]+fibSequence[1];
  fibSequence.unshift(sum);
}

for (var i = 0; i < fibSequence.length; i++) {
  if (fibSequence[i] % 2 == 0) {
    total += fibSequence[i];
  }
}

console.log(total)